name: CI

on:
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.18-bullseye
      env:
        FOO: Bar
        REVISION: $GITHUB_SHA
    steps:
      - uses: actions/checkout@v3
      - name: install deps
        run: |
          apt update && apt install jq -y
          make REVISION=$GITHUB_SHA install
      - name: echo REVISION
        run: | 
          echo "$GITHUB_SHA should match the commit ID of feature branch"
          echo "github.sha -> ${{ github.sha }}"
          echo "GITHUB_SHA -> $GITHUB_SHA"
      - name: make test 
        run: |
          make REVISION=$GITHUB_SHA test
      - name: Publish Junit style Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/report-junit.xml'
      # - name: release library
      #   run: make REVISION=$GITHUB_SHA tag
      # - name: release binary
      #   run: |
      #     make REVISION=$GITHUB_SHA PAT=${{ secrets.GITHUB_TOKEN }} cross-build
      #     make REVISION=$GITHUB_SHA PAT=${{ secrets.GITHUB_TOKEN }} release
