name: CI

on:
  pull_request:
    branches: [ master, main ]

permissions:
  pull-requests: read

jobs:
  set-deps-dotnet-poop-here:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:6.0 
      env:
        FOO: Bar
        REVISION: $GITHUB_SHA
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: '5.x'
      - name: Set SemVer Version
        uses: gittools/actions/gitversion/execute@v0.9.15
        id: gitversion

      - name: echo VERSIONS
        run: | 
          echo "REVISION  -> $GITHUB_SHA"
          echo "VERSION -> $GITVERSION_SEMVER"
  run-test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.19-bullseye
      env:
        FOO: Bar
        REVISION: $GITHUB_SHA
    needs: set-deps-dotnet-poop-here
    env:
      SEMVER: ${{ needs.set-deps-dotnet-poop-here.outputs.semVer }}
    steps:
      - uses: actions/checkout@v3
      - name: echo VERSIONS
        run: | 
          echo "REVISION  -> $GITHUB_SHA"
          echo "VERSION -> $SEMVER"
      - name: install cli deps
        run: |
          apt update && apt install jq -y
      - name: make test 
        run: |
          make REVISION=$GITHUB_SHA test
      - name: Publish Junit style Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/report-junit.xml'
      - name: Analyze with SonarCloud         
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          # Additional arguments for the sonarcloud scanner
          args:             
            # mandatory
            -Dsonar.projectVersion=$SEMVER-pr
            -Dsonar.go.coverage.reportPaths=/github/workspace/controller/.coverage/out,/github/workspace/seeder/.coverage/out
