name: CI-ScratchPad-PR

on:
  pull_request:
    branches: [ master, main ]

jobs:
  kind-test-scratch-pad:
    runs-on: ubuntu-latest
    container:
      image: dnitsch/gha-dind:0.0.6
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      options: --privileged=true --group-add=docker
    env:
      GOVCS: false
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: DL tools
        run: |
          curl -LO https://dl.k8s.io/release/v1.26.1/bin/linux/amd64/kubectl
          install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.17.0/kind-linux-amd64
          install -o root -g root -m 0755 kind /usr/local/bin/kind
      - name: Get KubeConfig 
        run: | 
          export KUBECONFIG=$HOME/.kube/config
          export KIND_EXPERIMENTAL_DOCKER_NETWORK=${{ job.container.network }}
          echo 'kind: Cluster
          apiVersion: kind.x-k8s.io/v1alpha4
          networking:
            apiServerAddress: "127.0.0.1"
            apiServerPort: 6443' > $PWD/kind-config.yml
          
          cat $PWD/kind-config.yml
          
          kind create cluster --kubeconfig=$KUBECONFIG --config=$PWD/kind-config.yml

          echo "get internal"
          kind get kubeconfig --internal
          echo "get normal"
          kind get kubeconfig
          echo "======= get internal IP ======="
          docker inspect "kind-control-plane" --format "{{ .NetworkSettings.Networks.kind.IPAddress }}"

          kubectl config set-cluster kind-kind --server=https://kind-control-plane:6443
          
          kubectl get pods -n kube-system
          kubectl cluster-info

          kubectl apply -f ./kubebuilder-controller/config/crd/bases/seeder.dnitsch.net_reststrategies.yaml
